routes/web.php
<?php

use App\Http\Controllers\HomeController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes( [
    'register' => false
] );

Route::get('/', 'HomeController');
Route::get('/home', 'HomeController')->name('home');

Route::resource('employees','EmployeeController')->middleware(['manage.employees','auth']);

Route::resource('companies','CompanyController')->middleware(['manage.companies','auth']);

Route::resource('accounts','AccountController')->middleware(['can:manage-app','auth']);


Route::prefix('accounts/{account}/change-password')->name('accounts')
    ->middleware(['can:manage-app','auth'])
    ->group(function(){

        Route::get('','AccountController@showChangePassword')->name('.change_password');
        Route::post('','AccountController@updatePassword')->name('.update_password');

    });

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    const ROLE_ADMIN = 'admin';
    const ROLE_NORMAL = 'normal';


    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'role'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function isAdministrator()
    {
        return $this->role == self::ROLE_ADMIN;
    }

    public function getRoleTextAttribute()
    {
        switch ($this->role) {
            case static::ROLE_NORMAL:
                $role = 'Normal';
                break;

            case static::ROLE_ADMIN:
                $role = 'Administrator';
                break;
            default:
                $role = '';
                break;
        }
        
        return $role;
    }
}

app/Http/Controllers/AccountController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\AccountStoreRequest;
use App\Http\Requests\AccountUpdatePasswordRequest;
use App\Http\Requests\AccountUpdateRequest;
use App\Http\Requests\IndexRequest;
use App\User;

class AccountController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(IndexRequest $request)
    {
        $keyword = $request->q;
        $limit = $request->getLimit();

        $accounts = User::on();

        if($keyword)
        {
            $accounts->where(function($accounts) use($keyword){

                $accounts->orWhere('name','like',"%{$keyword}%")
                        ->orWhere('email','like',"%$keyword%");

            });
        }

        $accounts = $accounts->paginate($limit);

        return view('accounts.index', [ 'accounts' => $accounts ] );
    }

    /**
     * Show the form for creating a new account.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $roles = $this->roles();

        return view('accounts.create', [ 'roles' => $roles ]);
    }

    /**
     * Store a newly created account
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(AccountStoreRequest $request)
    {
        $account = User::create($request->data());
        return redirect()->route('accounts.create')->with('success','User saved successfully.');
    }

    /**
     * Display the specified account
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(User $account)
    {
        return view('accounts.view', [ 'account' => $account ] );
    }

    /**
     * Show the form for editing the account
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(User $account)
    {
        $roles = $this->roles();

        return view('accounts.edit', [ 'roles' => $roles, 'account' => $account ] );
    }

    /**
     * Update account information
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(AccountUpdateRequest $request, User $account)
    {
        $account->name = $request->name;
        $account->email = $request->email;
        $account->role = $request->role;

        if($account->isDirty('role') && $account->role == User::ROLE_NORMAL)
        {
            if($this->hasOnlyOneAdmin())
                return redirect()->route('accounts.edit', $account->id)
                                ->withInput()
                                ->with('warning', 'Sorry but the system must have at least one administrator account.');
        }
        
        $account->save();

        return redirect()->route('accounts.edit', $account->id)->with('success','User information updated.');
    }

    /**
     * Delete the account from the database
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $account)
    {
        if($this->hasOnlyOneAdmin() && $account->role == User::ROLE_ADMIN)
            return redirect()->route('accounts.show', $account->id)
                        ->with('warning', 'Sorry but the system must have at least one administrator account.');

        $account->delete();

        return redirect()->route('accounts.index')->with('success','User deleted.');
    }

    /**
     * Show the account change password form
     * 
     * @param \App\User $account
     * 
     * @return \Illuminate\Http\Response
     */
    public function showChangePassword(User $account)
    {
        return view('accounts.change_password', ['account' => $account]);
    }

    /**
     * Update the account password
     * 
     * @param \App\Http\Requests\AccountUpdatePasswordRequest $request
     * @param \App\User $account
     * 
     * @return \Illuminate\Http\Response
     */
    public function updatePassword(AccountUpdatePasswordRequest $request, User $account)
    {
        $account->password = bcrypt($request->password);
        $account->save();

        return redirect()->route('accounts.change_password', $account->id)->with('success', 'Account password updated.');
    }

    /**
     * Generate account role list
     * 
     * @return Array
     */
    public function roles()
    {
        return [
            'Administrator' => User::ROLE_ADMIN,
            'Normal' => User::ROLE_NORMAL
        ];
    }

    /**
     * 
     */
    public function hasOnlyOneAdmin()
    {
        if(User::whereRole(User::ROLE_ADMIN)->count() == 1)
            return true;

        return false;
    }
}

resources/views/accounts/change_password.blade.php
@extends('layouts.app',[
'title' => 'Change Password'
])

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">

            @if( session('success') )
            <div class="alert alert-success" role="alert">
                {{ @session('success') }}
            </div>
            @endif

            @if( session('warning') )
            <div class="alert alert-warning" role="alert">
                {{ @session('warning') }}
            </div>
            @endif

            <div class="card">
                <div class="card-header">{{ __('Change Password') }}</div>
                <div class="card-body">
                    <form method="POST" action="{{ route('accounts.update_password', $account->id) }}">
                        @csrf
                        <div class="form-group row">
                            <label for="password"
                                class="col-md-4 col-form-label text-md-right">{{ __('Password') }}</label>

                            <div class="col-md-6">
                                <input id="password" type="password"
                                    class="form-control @error('password') is-invalid @enderror" name="password"
                                    required autocomplete="new-password">

                                @error('password')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="password-confirm"
                                class="col-md-4 col-form-label text-md-right">{{ __('Confirm Password') }}</label>

                            <div class="col-md-6">
                                <input id="password-confirm" type="password" class="form-control"
                                    name="password_confirmation" required autocomplete="new-password">
                            </div>
                        </div>


                        <button type="submit" class="btn btn-primary">Update Password</button>


                    </form>

                    <a href="{{ route('accounts.show', $account->id) }}">
                        {{ __('View Account') }}
                    </a>

                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/accounts/create.blade.php
@extends('layouts.app',[
'title' => 'Create Account'
])

@section('content')

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">

            @if( session('success') )
            <div class="alert alert-success" role="alert">
                {{ @session('success') }}
            </div>
            @endif

            @if( session('warning') )
            <div class="alert alert-warning" role="alert">
                {{ @session('warning') }}
            </div>
            @endif

            <div class="card">
                <div class="card-header">{{ __('Create Account') }}</div>
                <div class="card-body">
                    <form method="POST" action="{{ route('accounts.store') }}">
                        @csrf

                        @component('accounts.form')

                        @slot('name', old('name'))
                        @slot('email', old('email'))
                        @slot('role', old('role'))
                        @slot('roles', $roles)

                        @endcomponent

                        <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    {{ __('Save') }}
                                </button>
                            </div>
                        </div>


                        <a href="{{ route('accounts.index') }}">
                            {{ __('Return Account List') }}
                        </a>


                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/accounts/edit.blade.php
@extends('layouts.app',[
'title' => 'Edit Account | '. $account->name
])

@section('content')

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">

            @if( session('success') )
            <div class="alert alert-success" role="alert">
                {{ @session('success') }}
            </div>
            @endif

            @if( session('warning') )
            <div class="alert alert-warning" role="alert">
                {{ @session('warning') }}
            </div>
            @endif

            <div class="card">
                <div class="card-header">{{ __('Edit Account') }}</div>
                <div class="card-body">
                    <form method="POST" action="{{ route('accounts.update', $account->id) }}"
                        enctype="multipart/form-data">
                        @method('put')
                        @csrf

                        @component('accounts.form')

                        @slot('show_password_field', false)
                        @slot('name', old('name') ?? $account->name) 
                        @slot('email', old('email') ?? $account->email) 
                        @slot('role', old('role') ?? $account->role)
                        @slot('roles', $roles)

                        @endcomponent

                        <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    {{ __('Save') }}
                                </button>
                            </div>
                        </div>

                        <a href="{{ route('accounts.show', $account->id) }}">
                            {{ __('View Account') }}
                        </a>
                        <br>
                        <a href="{{ route('accounts.index') }}">
                            {{ __('Return Account List') }}
                        </a>
                        
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/accounts/form.blade.php
<div class="form-group row">
    <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('Name') }}</label>

    <div class="col-md-6">
        <input id="name" type="text" class="form-control @error('name') is-invalid @enderror" name="name"
            value="{{ $name }}" autocomplete="name" required autofocus>

        @error('name')
        <span class="invalid-feedback" role="alert">
            <strong>{{ $message }}</strong>
        </span>
        @enderror
    </div>
</div>


<div class="form-group row">
    <label for="email" class="col-md-4 col-form-label text-md-right">{{ __('E-Mail Address') }}</label>

    <div class="col-md-6">
        <input id="email" type="email" class="form-control @error('email') is-invalid @enderror" name="email"
            value="{{ $email }}" required autocomplete="email">

        @error('email')
        <span class="invalid-feedback" role="alert">
            <strong>{{ $message }}</strong>
        </span>
        @enderror
    </div>
</div>


@if($show_password_field ?? true )
<div class="form-group row">
    <label for="password" class="col-md-4 col-form-label text-md-right">{{ __('Password') }}</label>

    <div class="col-md-6">
        <input id="password" type="password" class="form-control @error('password') is-invalid @enderror"
            name="password" required autocomplete="new-password">

        @error('password')
        <span class="invalid-feedback" role="alert">
            <strong>{{ $message }}</strong>
        </span>
        @enderror
    </div>
</div>

<div class="form-group row">
    <label for="password-confirm" class="col-md-4 col-form-label text-md-right">{{ __('Confirm Password') }}</label>

    <div class="col-md-6">
        <input id="password-confirm" type="password" class="form-control" name="password_confirmation" required
            autocomplete="new-password">
    </div>
</div>
@endif


<div class="form-group row">
    <label for="role" class="col-md-4 col-form-label text-md-right">{{ __('Role') }}</label>

    <div class="col-md-6">

        <select name="role" class="form-control" required>
            <option value="">-- Choose Company --</option>
            @foreach($roles as $key => $id)
            <option value="{{ $id }}" {{ $id == $role ? 'selected': '' }}>{{ $key }}
            </option>
            @endforeach
        </select>

        @error('role')
        <span class="invalid-feedback" role="alert">
            <strong>{{ $message }}</strong>
        </span>
        @enderror
    </div>
</div>

resources/views/accounts/index.blade.php
@extends('layouts.app',[
'title' => 'Manage Accounts'
])

@section('content')
<div class="container">


    @if( session('success') )
    <div class="alert alert-success" role="alert">
        {{ @session('success') }}
    </div>
    @endif

    <div class="card">
        <div class="card-header">
            {{ __('Manage Accounts') }}
            <div class="float-right">
                <a href="{{ route('accounts.create') }}">Create New Account</a>
            </div>
        </div>

        <div class="card-body">

            <form action="{{ route('accounts.index') }}" class="form-inline pb-3" method="get">

                <div class="form-group"> 
                    <div class="input-group">
                    <label for="q" class="sr-only">Search</label>

                        <input class="form-control" value="{{ request()->q }}" type="text" name="q"
                            placeholder="Search...">
                        <div class="input-group-append">
                            <button class="btn btn-primary">Search</button>
                        </div>
                    </div>
                </div>

                <div class="form-group mx-sm-3"> 
                    <label for="limit" class="sr-only">Limit</label>
                    @component('components.input_limit')
                    @slot('limit', request()->limit ?? config('pagination.limit'))
                    @endcomponent
                </div>

            </form>

            <table class="table">
                <thead>
                    <tr>
                        <th>Id</th>
                        <th>Name</th>
                        <th>Email</th>
                        <th>Role</th>
                        <th>Action</th>
                    </tr>
                </thead>

                <tbody>
                    @foreach($accounts as $account)
                    <tr>
                        <td>{{ $account->id }}</td>
                        <td>{{ $account->name }}</td>
                        <td>{{ $account->email }}</td>
                        <td>{{ $account->role_text }}</td>
                        <td>

                            <a href="{{ route('accounts.edit', $account->id) }}" class="btn btn-warning btn-sm">Edit</a>

                            <a href="{{ route('accounts.show' ,$account->id) }}" class="btn btn-primary btn-sm">View</a>
                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>

            {{ $accounts->appends([ 'q' => request()->q, 'limit' => request()->limit ])->links() }}

        </div>
    </div>

</div>
@endsection

resources/views/accounts/view.blade.php
@extends('layouts.app',[
'title' => "Employee {$account->full_name}"
])

@section('content')

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">

        @if( session('warning') )
            <div class="alert alert-warning" role="alert">
                {{ @session('warning') }}
            </div>
            @endif
            
            <div class="card">
                <div class="card-header"><a title="Account Id"
                        href="{{ route('accounts.show', $account->id) }}">{{ $account->id }}</a> -
                    {{ __($account->name) }}</div>
                <div class="card-body">
                    <dl class="row">
                        <dt class="col-sm-3">Name</dt>
                        <dd class="col-sm-9">{{ $account->name }}</dd>
                        <dt class="col-sm-3">Email</dt>
                        <dd class="col-sm-9"><a href="mailto:{{ $account->email }}">{{ $account->email }}</a></dd>
                        <dt class="col-sm-3">Role</dt>
                        <dd class="col-sm-9">{{ $account->role_text }}</dd>
                        <dt class="col-sm-3">Last Edit</dt>
                        <dd class="col-sm-9 small">{{ $account->updated_at }}</dd>
                    </dl>

                    <a href="{{ route('accounts.edit', $account->id) }}" class="btn btn-warning">Edit</a>
                    <a href="{{ route('accounts.change_password', $account->id) }}" class="btn btn-primary">Chage
                        Password</a>

                    <form action="{{ route('accounts.destroy', $account->id) }}" method="post">
                        @csrf
                        @method('delete')
                        <button type="submit" class="btn btn-danger">Delete</button>
                    </form>



                    <a href="{{ route('accounts.index') }}">
                        {{ __('Return Account List') }}
                    </a>

                </div>
            </div>
        </div>
    </div>
</div>

@endsection