routes/web.php
<?php

use App\Http\Controllers\HomeController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes( [
    'register' => false
] );

Route::get('/', 'HomeController');
Route::get('/home', 'HomeController')->name('home');

Route::resource('employees','EmployeeController')->middleware(['manage.employees','auth']);

Route::resource('companies','CompanyController')->middleware(['manage.companies','auth']);

Route::resource('accounts','AccountController')->middleware(['can:manage-app','auth']);


Route::prefix('accounts/{account}/change-password')->name('accounts')
    ->middleware(['can:manage-app','auth'])
    ->group(function(){

        Route::get('','AccountController@showChangePassword')->name('.change_password');
        Route::post('','AccountController@updatePassword')->name('.update_password');

    });

app/Company.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Company extends Model
{
    protected $fillable = [
        'name', 'email', 'website'
    ];

    public function employees()
    {
        return $this->hasMany('App\Employee','company_id');
    }

    public function image()
    {
        return $this->morphOne('App\Image', 'imageable')->latest();
    }

    public function images()
    {
        return $this->morphMany('App\Image', 'imageable');
    }

    public function getHasLogoAttribute()
    {
        return $this->image != null;
    }

    public function getHasEmployeesAttribute()
    {
        return $this->employees()->count() != 0;
    }

    /**
     * Return the first and last words initial characters in the name attribute
     * If contains one word, return the single letter
     */
    public function getNameInitialsAttribute()
    {
        $names = explode(" ", $this->name);
        $count_names = count($names);
        
        $first_in = substr($names[0], 0, 1); // First initial

        if($count_names == 1)
            return $first_in;

        return strtoupper($first_in .  substr($names[count($names)-1], 0, 1));
    }
}

app/Employee.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Employee extends Model
{    
    protected $fillable = [
        'first_name', 'last_name', 'company_id', 'email', 'phone'
    ];

    /**
     * Generate full name of the employee
     * 
     * @return string FullName
     */
    public function getFullNameAttribute()
    {
        return "$this->first_name $this->last_name";
    }

    public function company()
    {
        return $this->belongsTo('App\Company', 'company_id');
    }
}

app/Http/Controllers/CompanyController.php
<?php

namespace App\Http\Controllers;

use App\Company;
use App\Helpers\ImageUploader;
use App\Http\Requests\CompanyStoreRequest;
use App\Http\Requests\CompanyUpdateRequest;
use App\Http\Requests\IndexRequest;
use DB;

class CompanyController extends Controller
{
    /**
     * Display a listing of companies
     *
     * @return \Illuminate\Http\Response
     */
    public function index(IndexRequest $request)
    {
        $keyword = $request->q;
        $limit = $request->getLimit();

        $companies = Company::on();

        if($keyword)
        {
            $companies->where(function($companies) use($keyword){

                $companies->orWhere('name','like',"%$keyword%")
                        ->orWhere('email','like',"%$keyword%");

            });
        }

        $companies = $companies->paginate($limit);

        return view('companies.index', [ 'companies'=> $companies]);
    }

    /**
     * Show the form for creating a new company.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('companies.create');
    }

    /**
     * Store a newly created company in database.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CompanyStoreRequest $request)
    {
        DB::beginTransaction();

        $company = Company::create($request->data());
        $upload = new ImageUploader($request->image, $company);
        $upload->save();

        DB::commit();

        return redirect()->route('companies.create')->with('success','Company successfully saved.');
    }

    /**
     * Display the specified company.
     *
     * @param  int  $company
     * @return \Illuminate\Http\Response
     */
    public function show(Company $company)
    {
        $employees = $company->employees()->paginate(config('pagination.limit'));

        return view('companies.view', [
            'company' => $company,
            'employees' => $employees
        ]);
    }

    /**
     * Show the form for editing the specified company.
     *
     * @param  int  $company
     * @return \Illuminate\Http\Response
     */
    public function edit(Company $company)
    {
        return view('companies.edit', [
            'company' => $company
        ]);
    }

    /**
     * Update the specified company in database.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $company
     * @return \Illuminate\Http\Response
     */
    public function update(CompanyUpdateRequest $request, Company $company)
    {
        $company->update($request->data());

        if( ! $company->wasChanged() && ! $request->image)
        {
            return redirect()->route('companies.edit', $company->id)
                             ->with('warning', 'There are no changes made');
        }

        if($request->image)
        {
            $upload = new ImageUploader($request->image, $company);
            $upload->save();
        }

        return redirect()->route('companies.edit', $company->id)
                         ->with('success', 'Company successfully updated.');
    }

    /**
     * Remove the specified company from storage.
     *
     * @param  int  $company
     * @return \Illuminate\Http\Response
     */
    public function destroy(Company $company)
    {
        $company->delete();

        return redirect()->route('companies.index')->with('success','Company successfully deleted.');
    }
}

resources/views/companies/create.blade.php
@extends('layouts.app',[
    'title' => 'Create Company'
])

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">

            @if( session('success') )
            <div class="alert alert-success" role="alert">
                {{ @session('success') }}
            </div>
            @endif

            <div class="card">
                <div class="card-header">{{ __('Create Company') }}</div>
                <div class="card-body">
                    <form method="POST" action="{{ route('companies.store') }}" enctype="multipart/form-data">
                        @csrf
                        
                        @component('companies.form')

                            @slot('name', old('name'))
                            @slot('email', old('email'))
                            @slot('website', old('website'))

                            @slot('logo_attr','required')
                        @endcomponent


                        <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    {{ __('Save') }}
                                </button>
                            </div>
                        </div>

                        <a href="{{ route('companies.index') }}">
                            {{ __('Return Company List') }}
                        </a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/companies/edit.blade.php
@extends('layouts.app',[
'title' => 'Edit Company | '. $company->name
])

@section('content')

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">

            @if( session('success') )
            <div class="alert alert-success" role="alert">
                {{ @session('success') }}
            </div>
            @endif

            @if( session('warning') )
            <div class="alert alert-warning" role="alert">
                {{ @session('warning') }}
            </div>
            @endif

            <div class="card">
                <div class="card-header">{{ __('Edit Company') }}</div>
                <div class="card-body">
                    <form method="POST" action="{{ route('companies.update', $company->id) }}"
                        enctype="multipart/form-data">
                        @method('patch')
                        @csrf

                        @component('companies.form')

                        @slot('name', old('name') ?? $company->name)
                        @slot('email', old('email') ?? $company->email)
                        @slot('website', old('website') ?? $company->website)

                        @endcomponent

                        <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    {{ __('Save') }}
                                </button>
                            </div>
                        </div>

                        <a href="{{ route('companies.show', $company->id) }}">
                            {{ __('View company') }}
                        </a>
                        <br>
                        <a href="{{ route('companies.index') }}">
                            {{ __('Return Company List') }}
                        </a>


                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/companies/form.blade.php
<div class="form-group row">
    <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('Name') }}</label>

    <div class="col-md-6">
        <input id="name" type="text" class="form-control @error('name') is-invalid @enderror" name="name"
            value="{{ $name }}" autocomplete="name" required autofocus>

        @error('name')
        <span class="invalid-feedback" role="alert">
            <strong>{{ $message }}</strong>
        </span>
        @enderror
    </div>
</div>

<div class="form-group row">
    <label for="email" class="col-md-4 col-form-label text-md-right">{{ __('E-Mail Address') }}</label>

    <div class="col-md-6">
        <input id="email" type="email" class="form-control @error('email') is-invalid @enderror" name="email"
            value="{{ $email }}" required autocomplete="email">

        @error('email')
        <span class="invalid-feedback" role="alert">
            <strong>{{ $message }}</strong>
        </span>
        @enderror
    </div>
</div>

<div class="form-group row">
    <label for="website" class="col-md-4 col-form-label text-md-right">{{ __('Website') }}</label>

    <div class="col-md-6">
        <input id="website" type="text" value="{{ $website }}"
            class="form-control @error('website') is-invalid @enderror" name="website" required>

        @error('website')
        <span class="invalid-feedback" role="alert">
            <strong>{{ $message }}</strong>
        </span>
        @enderror
    </div>
</div>

<div class="form-group row">
    <label for="image" class="col-md-4 col-form-label text-md-right">{{ __('Logo') }}</label>

    <div class="col-md-6">
        <input id="image" type="file" class="@error('image') is-invalid @enderror" name="image" {{ $logo_attr ?? '' }} >
        <span class="small">Image must be 100x100 dimension and 2MB max file size</span>

        @error('image')
        <span class="invalid-feedback" role="alert">
            <strong>{{ $message }}</strong>
        </span>
        @enderror
    </div>
</div>

resources/views/companies/index.blade.php
@extends('layouts.app',[
'title' => 'Manage Companies'
])

@section('content')
<div class="container">


    @if( session('success') )
    <div class="alert alert-success" role="alert">
        {{ @session('success') }}
    </div>
    @endif

    <div class="card">
        <div class="card-header">
            {{ __('Manage Companies') }}
            <div class="float-right">
                <a href="{{ route('companies.create') }}">Create New Company</a>
            </div>
        </div>

        <div class="card-body">

            <form action="{{ route('companies.index') }}" class="form-inline pb-3" method="get">
            
                <div class="form-group">
                    <label for="q" class="sr-only">Search</label>
                    <div class="input-group">
                        <input class="form-control" value="{{ request()->q }}" type="text" name="q"
                            placeholder="Search...">
                        <div class="input-group-append">
                            <button class="btn btn-primary">Search</button>
                        </div>
                    </div>
                </div>

                <div class="form-group mx-sm-3"> 
                    <label for="limit" class="sr-only">Limit</label>
                    @component('components.input_limit')
                    @slot('limit', request()->limit ?? config('pagination.limit'))
                    @endcomponent
                </div>

            </form>

            <table class="table">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Email</th>
                        <th>Website</th>
                        <th>Created At</th>
                        <th>Action</th>
                    </tr>
                </thead>

                <tbody>
                    @foreach($companies as $company)
                    <tr>
                        <td>
                            @if($company->image)
                            <img class="profile-image rounded-circle" src="{{ $company->image->url }}"
                                alt="{{ $company->name }} Logo">
                            @else
                            <div class="profile-image initials">{{ $company->name_initials }}</div>
                            @endif

                            <div>{{ $company->name }}</div>
                        </td>
                        <td>
                            <a href="mailto:{{ $company->email }}">{{ $company->email }}</a>
                        </td>
                        <td>
                            <a target="_blank" href="{{ $company->website }}">{{ $company->website }}</a>
                        </td>
                        <td>{{ $company->updated_at }}</td>
                        <td>

                            <a href="{{ route('companies.edit', $company->id) }}"
                                class="btn btn-warning btn-sm">Edit</a>

                            <a href="{{ route('companies.show' ,$company->id) }}"
                                class="btn btn-primary btn-sm">View</a>
                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
            {{ $companies->appends([ 'q' => request()->q, 'limit' => request()->limit ])->links() }}
        </div>
    </div>
</div>
@endsection

resources/views/companies/view.blade.php
@extends('layouts.app',[
'title' => $company->name
])

@section('content')

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">

            <div class="card">
                <div class="card-header">{{ __( $company->name ) }}</div>
                <div class="card-body">

                    @if($company->image)
                    <img src="{{ $company->image->url }}" alt="{{ $company->name }} Logo">
                    @endif
                    <dl class="row">

                        <dt class="col-sm-3">Name</dt>
                        <dd class="col-sm-9">{{ $company->name }}</dd>

                        <dt class="col-sm-3">Email</dt>
                        <dd class="col-sm-9"><a href="mailto:{{ $company->email }}">{{ $company->email }}</a></dd>

                        <dt class="col-sm-3">Website</dt>
                        <dd class="col-sm-9"><a target="_blank"
                                href="{{ $company->website }}">{{ $company->website }}</a></dd>

                    </dl>

                    <div class="btn-group" role="group" aria-label="Basic example">
                        <a href="{{ route('companies.edit', $company->id) }}" class="btn btn-warning">Edit</a>
                        <form action="{{ route('companies.destroy', $company->id) }}" method="post">
                            @csrf
                            @method('delete')
                            <button type="submit" class="btn btn-danger">Delete</button>
                        </form>
                    </div>
                    
                </div>
            </div>

            <div class="p-2"></div>

            <div class="card">
                <div class="card-header">
                    Employees
                </div>
                <div class="card-body">
                    <table class="table">
                        <thead>
                            <tr>
                                <th>Id</th>
                                <th>Name</th>
                                <th>Email</th>
                                <th>Phone</th>
                            </tr>
                        </thead>

                        <tbody>
                            @foreach($employees as $employee)
                            <tr>
                                <td>{{ $employee->id }}</td>
                                <td>
                                    <a href="{{ route('employees.show', $employee->id) }}">
                                        {{ $employee->full_name }}
                                    </a>
                                </td>
                                <td>{{ $employee->email }}</td>
                                <td>{{ $employee->phone }}</td>

                            </tr>
                            @endforeach
                        </tbody>
                    </table>

                    {{ $employees->appends([ 'q' => request()->q ])->links() }}

                </div>
            </div>

        </div>
    </div>
</div>
@endsection