routes/web.php
<?php

use App\Http\Controllers\HomeController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes( [
    'register' => false
] );

Route::get('/', 'HomeController');
Route::get('/home', 'HomeController')->name('home');

Route::resource('employees','EmployeeController')->middleware(['manage.employees','auth']);

Route::resource('companies','CompanyController')->middleware(['manage.companies','auth']);

Route::resource('accounts','AccountController')->middleware(['can:manage-app','auth']);


Route::prefix('accounts/{account}/change-password')->name('accounts')
    ->middleware(['can:manage-app','auth'])
    ->group(function(){

        Route::get('','AccountController@showChangePassword')->name('.change_password');
        Route::post('','AccountController@updatePassword')->name('.update_password');

    });

app/Employee.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Employee extends Model
{    
    protected $fillable = [
        'first_name', 'last_name', 'company_id', 'email', 'phone'
    ];

    /**
     * Generate full name of the employee
     * 
     * @return string FullName
     */
    public function getFullNameAttribute()
    {
        return "$this->first_name $this->last_name";
    }

    public function company()
    {
        return $this->belongsTo('App\Company', 'company_id');
    }
}

app/Http/Controllers/EmployeeController.php
<?php

namespace App\Http\Controllers;

use App\{Company, Employee};
use App\Http\Requests\EmployeeStoreRequest;
use App\Http\Requests\EmployeeUpdateRequest;
use App\Http\Requests\IndexRequest;

class EmployeeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(IndexRequest $request)
    {
        $keyword = $request->q;
        $limit = $request->getLimit();

        $employees = Employee::on();

        if($keyword)
        {
            $employees->where(function($employees) use($keyword){

                $employees->orWhereRaw("concat(first_name, '', last_name ) like '%{$keyword}%'")
                        ->orWhereRaw("concat(last_name, '', first_name ) like '%{$keyword}%'")
                        ->orWhere('email','like',"%$keyword%");

            });
        }

        $employees = $employees->paginate($limit);

        return view('employees.index', [ 'employees' => $employees ] );
    }

    /**
     * Show the form for creating a new employee.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $companies = Company::all();

        return view('employees.create', [ 'companies' => $companies ]);
    }

    /**
     * Store a newly created employee
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(EmployeeStoreRequest $request)
    {        
        $employee = new Employee;
        $employee->first_name = $request->first_name;
        $employee->last_name = $request->last_name;
        $employee->company_id = $request->company_id;
        $employee->email = $request->email;
        $employee->phone = $request->phone;
        $employee->save();
        
        return redirect()->route('employees.create')->with('success','Employee saved successfully.');
    }

    /**
     * Display the specified employee
     *
     * @param  int  $employee
     * @return \Illuminate\Http\Response
     */
    public function show(Employee $employee)
    {
        return view('employees.view', [ 'employee' => $employee ] );
    }

    /**
     * Show the form for editing the employee
     *
     * @param  int  $employee
     * @return \Illuminate\Http\Response
     */
    public function edit(Employee $employee)
    {
        $companies = Company::all();

        return view('employees.edit', [ 'companies' => $companies, 'employee' => $employee ] );
    }

    /**
     * Update employee information
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $employee
     * @return \Illuminate\Http\Response
     */
    public function update(EmployeeUpdateRequest $request, Employee $employee)
    {
        $employee->first_name = $request->first_name;
        $employee->last_name = $request->last_name;
        $employee->company_id = $request->company_id;
        $employee->email = $request->email;
        $employee->save();

        return redirect()->route('employees.edit', $employee->id)->with('success','Employee information updated.');
    }

    /**
     * Delete the employee from the database
     *
     * @param  int  $employee
     * @return \Illuminate\Http\Response
     */
    public function destroy(Employee $employee)
    {
        $employee->delete();

        return redirect()->route('employees.index')->with('success','Employee deleted.');
    }
}

resources/views/employees/create.blade.php
@extends('layouts.app',[
'title' => 'Create Employee'
])

@section('content')

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">

            @if( session('success') )
            <div class="alert alert-success" role="alert">
                {{ @session('success') }}
            </div>
            @endif

            @if( session('warning') )
            <div class="alert alert-warning" role="alert">
                {{ @session('warning') }}
            </div>
            @endif

            <div class="card">
                <div class="card-header">{{ __('Edit Employee') }}</div>
                <div class="card-body">
                    <form method="POST" action="{{ route('employees.store') }}">
                        @csrf
                        
                        @component('employees.form')

                        @slot('first_name', old('first_name'))
                        @slot('last_name', old('last_name'))
                        @slot('email', old('email'))
                        @slot('company_id', old('company_id'))
                        @slot('phone', old('phone'))
                        @slot('companies', $companies)

                        @endcomponent

                        <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    {{ __('Save') }}
                                </button>
                            </div>
                        </div>

                   
                        <a href="{{ route('employees.index') }}">
                            {{ __('Return Employee List') }}
                        </a>


                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/employees/edit.blade.php
@extends('layouts.app',[
'title' => 'Edit Employee | '. $employee->full_name
])

@section('content')

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">

            @if( session('success') )
            <div class="alert alert-success" role="alert">
                {{ @session('success') }}
            </div>
            @endif

            @if( session('warning') )
            <div class="alert alert-warning" role="alert">
                {{ @session('warning') }}
            </div>
            @endif

            <div class="card">
                <div class="card-header">{{ __('Edit Employee') }}</div>
                <div class="card-body">
                    <form method="POST" action="{{ route('employees.update', $employee->id) }}"
                        enctype="multipart/form-data">
                        @method('patch')
                        @csrf

                        @component('employees.form')

                        @slot('first_name', old('first_name') ?? $employee->first_name)
                        @slot('last_name', old('last_name') ?? $employee->last_name)
                        @slot('email', old('email') ?? $employee->email)
                        @slot('company_id', old('company_id') ?? $employee->company_id)
                        @slot('phone', old('phone') ?? $employee->phone)
                        @slot('companies', $companies)

                        @endcomponent

                        <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    {{ __('Save') }}
                                </button>
                            </div>
                        </div>

                        <a href="{{ route('employees.show', $employee->id) }}">
                            {{ __('View Employee') }}
                        </a>
                        <br>
                        <a href="{{ route('employees.index') }}">
                            {{ __('Return Employee List') }}
                        </a>


                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/employees/form.blade.php
<div class="form-group row">
    <label for="first_name" class="col-md-4 col-form-label text-md-right">{{ __('First Name') }}</label>

    <div class="col-md-6">
        <input id="first_name" type="text" class="form-control @error('first_name') is-invalid @enderror"
            name="first_name" value="{{ $first_name }}" autocomplete="first_name" required autofocus>

        @error('first_name')
        <span class="invalid-feedback" role="alert">
            <strong>{{ $message }}</strong>
        </span>
        @enderror
    </div>
</div>

<div class="form-group row">
    <label for="last_name" class="col-md-4 col-form-label text-md-right">{{ __('Last Name') }}</label>

    <div class="col-md-6">
        <input id="last_name" type="text" class="form-control @error('last_name') is-invalid @enderror" name="last_name"
            value="{{ $last_name }}" autocomplete="last_name" required autofocus>

        @error('last_name')
        <span class="invalid-feedback" role="alert">
            <strong>{{ $message }}</strong>
        </span>
        @enderror
    </div>
</div>



<div class="form-group row">
    <label for="email" class="col-md-4 col-form-label text-md-right">{{ __('E-Mail Address') }}</label>

    <div class="col-md-6">
        <input id="email" type="email" class="form-control @error('email') is-invalid @enderror" name="email"
            value="{{ $email }}" required autocomplete="email">

        @error('email')
        <span class="invalid-feedback" role="alert">
            <strong>{{ $message }}</strong>
        </span>
        @enderror
    </div>
</div>

<div class="form-group row">
    <label for="phone" class="col-md-4 col-form-label text-md-right">{{ __('Phone') }}</label>

    <div class="col-md-6">
        <input id="phone" type="text" value="{{ $phone }}" class="form-control @error('phone') is-invalid @enderror"
            name="phone" required>
        <span class="small">9 Digit Phone #</span>
        @error('phone')
        <span class="invalid-feedback" role="alert">
            <strong>{{ $message }}</strong>
        </span>
        @enderror
    </div>
</div>

<div class="form-group row">
    <label for="company_id" class="col-md-4 col-form-label text-md-right">{{ __('Company') }}</label>

    <div class="col-md-6">

        <select name="company_id" class="form-control" required>
            <option value="">-- Choose Company --</option>
            @foreach($companies as $company)
            <option value="{{ $company->id }}" {{ $company->id == $company_id ? 'selected': '' }}>{{ $company->name }}
            </option>
            @endforeach
        </select>

        @error('company_id')
        <span class="invalid-feedback" role="alert">
            <strong>{{ $message }}</strong>
        </span>
        @enderror
    </div>
</div>

resources/views/employees/index.blade.php
@extends('layouts.app',[
'title' => 'Manage Employees'
])

@section('content')
<div class="container">


    @if( session('success') )
    <div class="alert alert-success" role="alert">
        {{ @session('success') }}
    </div>
    @endif

    <div class="card">
        <div class="card-header">
            {{ __('Manage Employees') }}
            <div class="float-right">
                <a href="{{ route('employees.create') }}">Create New Employee</a>
            </div>
        </div>

        <div class="card-body">

            <form action="{{ route('employees.index') }}" class="form-inline pb-3" method="get">
            
                <div class="form-group">
                    <label for="q" class="sr-only">Search</label>
                    <div class="input-group">
                        <input class="form-control" value="{{ request()->q }}" type="text" name="q"
                            placeholder="Search...">
                        <div class="input-group-append">
                            <button class="btn btn-primary">Search</button>
                        </div>
                    </div>
                </div>

                <div class="form-group mx-sm-3"> 
                    <label for="limit" class="sr-only">Limit</label>
                    @component('components.input_limit')
                    @slot('limit', request()->limit ?? config('pagination.limit'))
                    @endcomponent
                </div>

            </form>

            <table class="table">
                <thead>
                    <tr>
                        <th>Id</th>
                        <th>Name</th>
                        <th>Email</th>
                        <th>Phone</th>
                        <th>Company</th>
                        <th>Action</th>
                    </tr>
                </thead>

                <tbody>
                    @foreach($employees as $employee)
                    <tr>
                        <td>{{ $employee->id }}</td>
                        <td>{{ $employee->full_name }}</td>
                        <td>{{ $employee->email }}</td>
                        <td>{{ $employee->phone }}</td>
                        <td>{{ $employee->company->name }}</td>
                        <td> 

                            <a href="{{ route('employees.edit', $employee->id) }}"
                                class="btn btn-warning btn-sm">Edit</a>

                            <a href="{{ route('employees.show' ,$employee->id) }}"
                                class="btn btn-primary btn-sm">View</a>
                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>

            {{ $employees->appends([ 'q' => request()->q, 'limit' => request()->limit ])->links() }}

        </div>
    </div>

</div>
@endsection

resources/views/employees/view.blade.php
@extends('layouts.app',[
'title' => "Employee {$employee->full_name}"
])

@section('content')

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">

            <div class="card">
                <div class="card-header">{{ __( $employee->full_name ) }}</div>
                <div class="card-body">
                    <dl class="row">
                        <dt class="col-sm-3">Name</dt>
                        <dd class="col-sm-9">{{ $employee->full_name }}</dd>

                        <dt class="col-sm-3">Email</dt>
                        <dd class="col-sm-9"><a href="mailto:{{ $employee->email }}">{{ $employee->email }}</a></dd>

                        <dt class="col-sm-3">Phone</dt>
                        <dd class="col-sm-9"><a target="_blank"
                                href="tel:{{ $employee->phone }}">{{ $employee->phone }}</a>
                        </dd>
                        <dt class="col-sm-3">Company</dt>
                        <dd class="col-sm-9"><a
                                href="{{ route('companies.show', $employee->company_id) }}">{{ $employee->company->name }}</a>
                        </dd>

                        <dt class="col-sm-3">Last Edit</dt>
                        <dd class="col-sm-9 small">{{ $employee->updated_at }}</dd>


                    </dl>

                    <a href="{{ route('employees.edit', $employee->id) }}" class="btn btn-warning">Edit</a>

                    <form action="{{ route('employees.destroy', $employee->id) }}" method="post">
                        @csrf
                        @method('delete')
                        <button type="submit" class="btn btn-danger">Delete</button>
                    </form>

                </div>
            </div>

            <div class="p-2"></div>
            <div class="card">
                <div class="card-header">Employee's Company</div>
                <div class="card-body">

                    @if($employee->company->image)
                    <img src="{{ $employee->company->image->url }}" alt="{{ $employee->company->name }} Logo">
                    @endif
                    <dl class="row">

                        <dt class="col-sm-3">Name</dt>
                        <dd class="col-sm-9">
                            <a title="View company" href="{{ route('companies.show', $employee->company_id) }}">
                                {{ $employee->company->name }}
                            </a>
                        </dd>

                        <dt class="col-sm-3">Email</dt>
                        <dd class="col-sm-9"><a
                                href="mailto:{{ $employee->company->email }}">{{ $employee->company->email }}</a></dd>

                        <dt class="col-sm-3">Website</dt>
                        <dd class="col-sm-9"><a target="_blank"
                                href="{{ $employee->company->website }}">{{ $employee->company->website }}</a></dd>

                    </dl>


                </div>
            </div>


        </div>
    </div>
</div>

@endsection